# Generated by Django 3.1.2 on 2023-02-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('authority', models.CharField(default=1, max_length=3, verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('price', models.FloatField(verbose_name='价格')),
                ('num_subscribers', models.IntegerField(verbose_name='订阅人数')),
                ('num_comments', models.IntegerField(verbose_name='评论人数')),
                ('category', models.CharField(max_length=255, verbose_name='类别')),
                ('language', models.CharField(max_length=32, verbose_name='语言')),
            ],
            options={
                'db_table': 'course_info',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('authority', models.CharField(default=0, max_length=3, verbose_name='权限')),
                ('gender', models.SmallIntegerField(choices=[(2, '女'), (1, '男')], verbose_name='性别')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='课程ID')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='学生ID')),
            ],
        ),
    ]
