# Generated by Django 3.1.2 on 2023-02-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230201_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128, verbose_name='评论')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='课程ID')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='学生ID')),
            ],
        ),
    ]
