# Generated by Django 3.1.2 on 2023-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230305_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_url',
            field=models.CharField(default='', max_length=64, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
