# Generated by Django 3.1.2 on 2023-03-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230306_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='headline',
            field=models.TextField(default='', verbose_name='概要'),
        ),
    ]
